# Simple workflow for deploying static content to GitHub Pages
name: Deploy Vue/Vite project to Pages # Mudei o nome para ser mais descritivo

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"] # Certifique-se de que este é o seu branch principal

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # -- ADICIONE ESTES DOIS PASSOS PARA CONSTRUIR SEU PROJETO --
      - name: Setup Node.js
        uses: actions/setup-node@v4 # Use uma versão mais recente do Node.js
        with:
          node-version: '20' # Ou '18', '22' - escolha uma versão LTS que seu projeto usa

      - name: Install dependencies and Build project
        run: |
          npm install # Instala todas as dependências listadas no package.json
          npm run build # Executa o script 'build' que cria a pasta 'dist'
      # -- FIM DOS PASSOS ADICIONADOS --

      - name: Setup Pages
        uses: actions/configure-pages@v5 # Esta action está na v5, que é a mais recente

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3 # <--- MUDE AQUI PARA v3
        with:
          # Upload entire repository
          path: './dist' # Mantenha isso, pois é o caminho correto para a pasta gerada

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Esta action está na v4, que é a mais recente
